version: '3.8'

services:
  client:
    container_name: mp-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - "4200:4200"
  server:
    container_name: mp-server
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - client
    ports:
      - '3000:3000'


